services:
  postgres:
    image: postgres:17

    container_name: pintureria-postgres

    restart: unless-stopped

    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_DB: pintureria
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: