spring.application.name=pintureria-del-sur
# Configuración de la conexión a PostgreSQL
#spring.datasource.url=jdbc:postgresql://localhost:5432/pintureria
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#spring.datasource.driver-class-name=org.postgresql.Driver



# Creación automática de tablas basadas en tus Entityscd
#spring.jpa.hibernate.ddl-auto=update

# Mostrar las consultas SQL en la consola (opcional, útil para desarrollo)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true




spring.datasource.url=jdbc:postgresql://db.nwryuoewtfldbjcewmie.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=[contraseña]

# Esto le dice a Java que cree las tablas automáticamente al conectarse
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


