spring.application.name=pintureria-del-sur
# Configuración de la conexión a PostgreSQL
#spring.datasource.url=jdbc:postgresql://localhost:5432/pintureria
#spring.datasource.username=postgres
#spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver






# Mostrar las consultas SQL en la consola (opcional, útil para desarrollo)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true




spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SUPABASE_PASSWORD}

# Esto le dice a Java que cree las tablas automáticamente al conectarse
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.security=DEBUG
jwt.secret={JWT_PASSWORD}